services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: raffine-backend
    expose:
      - "8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: raffine-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped